### ISSUE TITLE
bug when i go on another world "Team line13 already exists in this scoreboard"

### ISSUE THREAD

**Issue by Xyness** [Oreoezi/HarmonyBoard#1]
I don't know why but i have this bug :
Team line13 already exists in this scoreboard

Version spigot : 1.18.1
Version of plugin : the last

**Comment by Oreoezi** [comment]
Hi, please provide more details such as a stack trace. That would be great

**Comment by Xyness** [comment]
Hey,
I use bungeecord for my server and this is logs : 
https://zupimages.net/up/22/04/cl3q.png

**Comment by Oreoezi** [comment]
> Hey, I use bungeecord for my server and this is logs : https://zupimages.net/up/22/04/cl3q.png

The plugin is designed for spigot

**Comment by Xyness** [comment]
Yes i know, i put the plugin in my spigot server but i use bungeecord too for my spigots servers

**Comment by Oreoezi** [comment]
> Yes i know, i put the plugin in my spigot server but i use bungeecord too for my spigots servers

try only putting the plugin in your servers and not in your proxy

**Comment by Xyness** [comment]
it works, i tried

**Comment by Xyness** [comment]
but i would like it to work with my proxy

**Comment by Oreoezi** [comment]
> but i would like it to work with my proxy

I am adding bungee support into my TODO list

**Comment by Xyness** [comment]
Okay thank's !
