### ISSUE TITLE
[BUG] No way to set a "Default" scoreboard

### ISSUE THREAD

**Issue by ItzSkyylark** [Oreoezi/HarmonyBoard#10]
### Description
Multiple scoreboards confuse server and it doesnt know which to set as your "Default" scoreboard.  Adding conditions like:
```
conditions:
 events:
  - JOINED
```
Does absolutely nothing but remove scoreboards entirely, to which logs display nothing and kicks ANYONE when you try and do /hboard reload

Should be an option in config to set a "default" scoreboard like

"Default board: default.yml"

Image when players being kicked on "/hboard reload"
![2022-06-24_20 38 49](https://user-images.githubusercontent.com/99417068/175751242-5b011d0c-31e4-4691-9f75-eb5e27483ba8.png)

**Comment by ItzSkyylark** [comment]
Heres the config.yml and 2 boards I have in play.... the "Astroblasters.yml" is only triggered on a single attraction, else its always default.yml.. also log added

*Had to change to .txt as github wont allow .yml
[default.txt](https://github.com/Oreoezi/HarmonyBoard/files/8983593/default.txt)
[config.txt](https://github.com/Oreoezi/HarmonyBoard/files/8983594/config.txt)
[astroblasters.txt](https://github.com/Oreoezi/HarmonyBoard/files/8983595/astroblasters.txt)
[latest.log](https://github.com/Oreoezi/HarmonyBoard/files/8983605/latest.log)

**Comment by Oreoezi** [comment]
> Heres the config.yml and 2 boards I have in play.... the "Astroblasters.yml" is only triggered on a single attraction, else its always default.yml.. also log added
> 
> *Had to change to .txt as github wont allow .yml [default.txt](https://github.com/Oreoezi/HarmonyBoard/files/8983593/default.txt) [config.txt](https://github.com/Oreoezi/HarmonyBoard/files/8983594/config.txt) [astroblasters.txt](https://github.com/Oreoezi/HarmonyBoard/files/8983595/astroblasters.txt) [latest.log](https://github.com/Oreoezi/HarmonyBoard/files/8983605/latest.log)

That seems to be an oversight with how the plugin handles 1.12 as stated in the error ``java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.ChatMessage.<init>(java.lang.String)``
Your conditions are set properly, although keep in mind the "joined" event triggers on join and shows the scoreboard for 10 seconds. I am sorry but I will recommend you downgrade to an earlier version until I can get this fixed, as I am quite busy atm.

**Comment by ItzSkyylark** [comment]
What version would be good? Or do I need to go one by one for a few hours?

**Comment by Oreoezi** [comment]
> What version would be good? Or do I need to go one by one for a few hours?

2.6.5
