### ISSUE TITLE
Reflections suggestions

### ISSUE THREAD

**Issue by iGabyTM** [Oreoezi/HarmonyBoard#2]
https://github.com/Oreoezi/HarmonyBoard/blob/c36bf2c7e6c973d723547df23aa04cb2f060d277/harmonyboard/src/main/java/me/oreoezi/harmonyboard/placeholders/Ping.java#L15-L16
Keep these two as constants instead of getting them every time you want to display the ping of a player.
This can be an example https://github.com/PlaceholderAPI/Player-Expansion/blob/f8c4afbe4ad01a91a247374978dd9ccebb5f8b25/src/main/java/com/extendedclip/papi/expansion/player/PlayerUtil.java#L50-L83

**Comment by Oreoezi** [comment]
Noted. Thanks for letting me know
