### ISSUE TITLE
Scoreboard will break after go to other dimensions

### ISSUE THREAD

**Issue by xMikux** [Oreoezi/HarmonyBoard#4]
Join the server

![image](https://user-images.githubusercontent.com/26039249/158634451-9059413c-6f3d-4063-a628-e68855ec5f8e.png)

After enter the nether

![image](https://user-images.githubusercontent.com/26039249/158634736-56a236a6-7dcf-44f8-a5f7-c90b71ed1b06.png)

**Comment by Oreoezi** [comment]
I will try to look into it and fix it, but I currently do not have a computer.

**Comment by Oreoezi** [comment]
Supposedly fixed it.
