### ISSUE TITLE
WIKI sucks, no one knows where your hex color support is

### ISSUE THREAD

**Issue by lizheyo77** [Oreoezi/HarmonyBoard#8]
WIKI sucks, no one knows where your hex color support is

**Comment by Oreoezi** [comment]
there is no hex color support as of now

**Comment by lizheyo77** [comment]
> 目前还没有十六进制颜色支持

Well, I see that spigot seems to have introduced

**Comment by Oreoezi** [comment]
> > 目前还没有十六进制颜色支持
> 
> Well, I see that spigot seems to have introduced

adding hex color codes in in my todo list. also by no hex support i mean my plugin does not have it, not that minecraft doesn't
