### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Climbby** [Oreoezi/HarmonyBoard#9]
### Description
Not Working

### Expected behaviour
It says plugin is disabled and its asking if its up to date

### System information
Plugin version: 2.7.0
Java version: Probably the latest since I'm running 1.19 
Has toggling enabled: [true]
Has events enabled: [false]

## Error logs
```
in a code block
```
or in a [gist](https://gist.github.com/Climbby/792d79f03b9cc8949c5cbd608fd7b31f)

## Configs
in a [gist](https://gist.github.com/Climbby/a189e3cb6b83040cefc8fe32be1cea94)

**Comment by Oreoezi** [comment]
As the templates suggest, you are supposed to provide a log of the errors you saw. i cannot help you out without knowing that

**Comment by Climbby** [comment]
The error is that its disabled, I don't know why and I don't know how to fix it
It doesnt show any more errors I don't think

**Comment by Oreoezi** [comment]
> The error is that its disabled, I don't know why and I don't know how to fix it
> It doesnt show any more errors I don't think
> 

Are you able to provide an error log? It should show up in your console

**Comment by Climbby** [comment]
I moved on from this plugin and I didn't find an error log, but thank you for trying to help. I will now be closing this and I will give you 5 stars on spigot for your efforts because the problem wasnt resolved probably because of me
